name: naliv-frontend
services:
- name: web
  source_dir: /
  github:
    repo: breadwithmeth/naliv-frontend
    branch: main
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: "production"
  - key: PORT
    value: "8080"
